/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ConexionBDD;
import Controlador.GuiaEnvioControlador;
import Modelo.Destinatario;
import Modelo.GuiaEnvio;
import Modelo.TarifaPeso;
import Modelo.Usuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author SUPERTRONICA
 */
public class GuiaEnvioVista extends javax.swing.JFrame {

    /**
     * Creates new form GuiaEnvioVista
     */
    public GuiaEnvioVista() {
        initComponents();
        txtRemitente.setText(Usuario.usuarioActual.getNombre());
        txtRemitente.setEditable(false);

        txtTelefonoRemitente.setText(Usuario.usuarioActual.getTelefono());
        txtTelefonoRemitente.setEditable(false);

        cargarDestinatarios();
        cargarTarifasPeso();

        txtEstado.setText("Pendiente");
        txtEstado.setEditable(false);

        txtIdGE.setEditable(false);
        txtFecha.setText(java.time.LocalDate.now().toString());
        txtFecha.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblGuiaEnvio = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblIdGE = new javax.swing.JLabel();
        lblRemitente = new javax.swing.JLabel();
        lblDireccionOrigen = new javax.swing.JLabel();
        lblDestinatario = new javax.swing.JLabel();
        lblDetallePaquete = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtIdGE = new javax.swing.JTextField();
        txtRemitente = new javax.swing.JTextField();
        txtDireccionOrigen = new javax.swing.JTextField();
        lblPeso = new javax.swing.JLabel();
        cmbPeso = new javax.swing.JComboBox<>();
        lblDireccionDestino = new javax.swing.JLabel();
        txtContactoDestinatario = new javax.swing.JTextField();
        lblLargo = new javax.swing.JLabel();
        lblAncho = new javax.swing.JLabel();
        lblAlto = new javax.swing.JLabel();
        txtLargo = new javax.swing.JTextField();
        txtValorAsegurado = new javax.swing.JTextField();
        txtAlto = new javax.swing.JTextField();
        lblContenidoDeclarado = new javax.swing.JLabel();
        txtContenidoDeclarado = new javax.swing.JTextField();
        lblValorAsegurado = new javax.swing.JLabel();
        lblDatosRemitente = new javax.swing.JLabel();
        lblDatosDestinatario = new javax.swing.JLabel();
        lblTelefonoRemitente = new javax.swing.JLabel();
        lblContactoDestinatario = new javax.swing.JLabel();
        txtTelefonoRemitente = new javax.swing.JTextField();
        txtDireccionDestino = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        lblTiempoEntrega = new javax.swing.JLabel();
        lblTipoDeEnvio = new javax.swing.JLabel();
        txtTiempoEntrega = new javax.swing.JTextField();
        rbEnvioNacional = new javax.swing.JRadioButton();
        rbEnvioInternacional = new javax.swing.JRadioButton();
        lblCostoTotal = new javax.swing.JLabel();
        txtCostoTotal = new javax.swing.JTextField();
        cmbNombresDestinatarios = new javax.swing.JComboBox<>();
        txtAncho = new javax.swing.JTextField();
        lblDetalleEnvio = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        btnCrearSolicitud = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblGuiaEnvio.setText("GUIA DE ENVIO");

        lblFecha.setText("FECHA:");

        lblIdGE.setText("ID:");

        lblRemitente.setText("REMITENTE:");

        lblDireccionOrigen.setText("DIRECCION DE ORIGEN:");

        lblDestinatario.setText("DESTINATARIO:");

        lblDetallePaquete.setText("DETALLE DEL PAQUETE");

        txtDireccionOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionOrigenActionPerformed(evt);
            }
        });

        lblPeso.setText("PESO:");

        cmbPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPesoActionPerformed(evt);
            }
        });

        lblDireccionDestino.setText("DIRECCION DE DESTINO:");

        lblLargo.setText("LARGO:");

        lblAncho.setText("ANCHO:");

        lblAlto.setText("ALTO:");

        txtLargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLargoActionPerformed(evt);
            }
        });

        lblContenidoDeclarado.setText("CONTENIDO DECLARADO:");

        lblValorAsegurado.setText("VALOR ASEGURADO:");

        lblDatosRemitente.setText("DATOS DE REMITENTE");

        lblDatosDestinatario.setText("DATOS DE DESTINATARIO");

        lblTelefonoRemitente.setText("CONTACTO:");

        lblContactoDestinatario.setText("CONTACTO:");

        lblEstado.setText("ESTADO:");

        lblTiempoEntrega.setText("TIEMPO DE ENTREGA:");

        lblTipoDeEnvio.setText("TIPO DE ENVIO:");

        buttonGroup1.add(rbEnvioNacional);
        rbEnvioNacional.setText("NACIONAL");
        rbEnvioNacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEnvioNacionalActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbEnvioInternacional);
        rbEnvioInternacional.setText("INTERNACIONAL");
        rbEnvioInternacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEnvioInternacionalActionPerformed(evt);
            }
        });

        lblCostoTotal.setText("COSTO TOTAL:");

        cmbNombresDestinatarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNombresDestinatariosActionPerformed(evt);
            }
        });

        lblDetalleEnvio.setText("DETALLE DEL ENVIO");

        btnCrearSolicitud.setText("CREAR SOLICITUD");
        btnCrearSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearSolicitudActionPerformed(evt);
            }
        });

        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(lblDatosRemitente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRemitente)
                                .addGap(83, 83, 83)
                                .addComponent(txtRemitente, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTelefonoRemitente)
                                        .addGap(63, 63, 63))
                                    .addComponent(lblDireccionOrigen, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTelefonoRemitente, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDireccionOrigen))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(lblIdGE)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdGE, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDestinatario)
                                .addGap(82, 82, 82))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblDireccionDestino)
                                .addGap(27, 27, 27)
                                .addComponent(txtDireccionDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cmbNombresDestinatarios, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblContactoDestinatario)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtContactoDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(66, 66, 66))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(79, 79, 79)
                            .addComponent(lblDetalleEnvio)
                            .addGap(165, 165, 165)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFecha)
                                .addGap(18, 18, 18)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDatosDestinatario))
                        .addGap(119, 119, 119))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(lblDetallePaquete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(cmbPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(lblAlto))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(txtAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(53, 53, 53)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblPeso)
                                        .addComponent(lblLargo))
                                    .addGap(18, 18, 18)
                                    .addComponent(txtLargo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAncho)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(txtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblContenidoDeclarado)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(lblValorAsegurado)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtValorAsegurado)
                                    .addComponent(txtContenidoDeclarado, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTiempoEntrega)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTiempoEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCostoTotal)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTipoDeEnvio)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbEnvioNacional)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbEnvioInternacional))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEstado)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCrearSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(lblGuiaEnvio)))
                .addGap(31, 38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGuiaEnvio)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdGE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdGE))
                        .addGap(18, 18, 18)
                        .addComponent(lblDatosRemitente)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRemitente)
                            .addComponent(txtRemitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefonoRemitente)
                            .addComponent(txtTelefonoRemitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDireccionOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDireccionOrigen)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFecha)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblDatosDestinatario)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDestinatario)
                            .addComponent(cmbNombresDestinatarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblContactoDestinatario)
                            .addComponent(txtContactoDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDireccionDestino)
                            .addComponent(txtDireccionDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDetallePaquete)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPeso)
                            .addComponent(cmbPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLargo)
                            .addComponent(txtLargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAlto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAncho)
                            .addComponent(txtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblContenidoDeclarado)
                            .addComponent(txtContenidoDeclarado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValorAsegurado)
                            .addComponent(txtValorAsegurado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(btnVolver)
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDetalleEnvio)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoDeEnvio)
                            .addComponent(rbEnvioNacional)
                            .addComponent(rbEnvioInternacional))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTiempoEntrega)
                            .addComponent(txtTiempoEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEstado)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCostoTotal)
                            .addComponent(txtCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(btnCrearSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPesoActionPerformed
        // TODO add your handling code here:
        calcularCostoTotal();
    }//GEN-LAST:event_cmbPesoActionPerformed

    private void txtLargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLargoActionPerformed

    private void txtDireccionOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionOrigenActionPerformed

    private void cmbNombresDestinatariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNombresDestinatariosActionPerformed
        // TODO add your handling code here:
        Destinatario seleccionado = (Destinatario) cmbNombresDestinatarios.getSelectedItem();

        if (seleccionado != null) {
            txtContactoDestinatario.setText(seleccionado.getContacto());
            txtDireccionDestino.setText(seleccionado.getDireccion());
            txtContactoDestinatario.setEditable(false);
            txtDireccionDestino.setEditable(false);
        }
    }//GEN-LAST:event_cmbNombresDestinatariosActionPerformed

    private void rbEnvioNacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEnvioNacionalActionPerformed
        // TODO add your handling code here:
        calcularCostoTotal();
    }//GEN-LAST:event_rbEnvioNacionalActionPerformed

    private void rbEnvioInternacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEnvioInternacionalActionPerformed
        // TODO add your handling code here:
        calcularCostoTotal();
    }//GEN-LAST:event_rbEnvioInternacionalActionPerformed

    private void btnCrearSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearSolicitudActionPerformed
        // TODO add your handling code here:
        Destinatario destinatarioSeleccionado = (Destinatario) cmbNombresDestinatarios.getSelectedItem();
        TarifaPeso pesoSeleccionado = (TarifaPeso) cmbPeso.getSelectedItem();

        if (destinatarioSeleccionado == null || pesoSeleccionado == null) {
            JOptionPane.showMessageDialog(null, "Seleccione destinatario y peso");
            return;
        }

        if (txtDireccionOrigen.getText().isEmpty()
                || txtLargo.getText().isEmpty()
                || txtAncho.getText().isEmpty()
                || txtAlto.getText().isEmpty()
                || txtValorAsegurado.getText().isEmpty()
                || txtContenidoDeclarado.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete todos los campos antes de continuar");
            return;
        }

        String tipoEnvio = rbEnvioInternacional.isSelected() ? "Internacional" : "Nacional";

        double peso = (pesoSeleccionado.getPesoMin() + pesoSeleccionado.getPesoMax()) / 2;
        double largo = Double.parseDouble(txtLargo.getText());
        double ancho = Double.parseDouble(txtAncho.getText());
        double alto = Double.parseDouble(txtAlto.getText());
        double valorAsegurado = Double.parseDouble(txtValorAsegurado.getText());
        double costoTotal = Double.parseDouble(txtCostoTotal.getText());

        GuiaEnvioControlador controlador = new GuiaEnvioControlador();
        boolean exito = controlador.crearGuiaEnvio(
                Usuario.usuarioActual.getIdUsuario(),
                destinatarioSeleccionado.getIdDestinatario(),
                txtDireccionOrigen.getText(),
                costoTotal,
                txtTiempoEntrega.getText(),
                tipoEnvio,
                peso, largo, ancho, alto,
                txtContenidoDeclarado.getText(),
                valorAsegurado
        );

        if (exito) {
            int idGenerado = controlador.getUltimoIdGenerado();
            String fechaGenerada = java.time.LocalDate.now().toString();

            txtIdGE.setText(String.valueOf(idGenerado));
            txtFecha.setText(fechaGenerada);

            // Generación automática del PDF
            javax.swing.JFileChooser selector = new javax.swing.JFileChooser();
            selector.setSelectedFile(new java.io.File("guia_envio_" + idGenerado + ".pdf"));

            int seleccion = selector.showSaveDialog(this);

            if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION) {
                String ruta = selector.getSelectedFile().getAbsolutePath();

                GuiaEnvio guia = new GuiaEnvio();
                guia.setIdGe(idGenerado);
                guia.setFechaDespacho(new java.util.Date());
                guia.setDireccionOrigen(txtDireccionOrigen.getText());
                guia.setTipoEnvio(tipoEnvio);
                guia.setTiempoEntrega(txtTiempoEntrega.getText());
                guia.setEstado(txtEstado.getText());
                guia.setCostoTotal(costoTotal);

                controlador.exportarPDF(guia, ruta);
            }

            JOptionPane.showMessageDialog(null,
                    "Guía de envío creada correctamente\nID: " + idGenerado);
        }

    }//GEN-LAST:event_btnCrearSolicitudActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        new MenuRemitente().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    private void cargarDestinatarios() {
        GuiaEnvioControlador controlador = new GuiaEnvioControlador();
        ArrayList<Destinatario> lista = controlador.listarDestinatarios();

        for (Destinatario d : lista) {
            cmbNombresDestinatarios.addItem(d);
        }
    }

    private void cargarTarifasPeso() {
        GuiaEnvioControlador controlador = new GuiaEnvioControlador();
        ArrayList<TarifaPeso> lista = controlador.listarTarifasPeso();

        for (TarifaPeso t : lista) {
            cmbPeso.addItem(t);
        }
    }

    private void calcularCostoTotal() {
        TarifaPeso pesoSeleccionado = (TarifaPeso) cmbPeso.getSelectedItem();

        if (pesoSeleccionado != null) {
            double costo = pesoSeleccionado.getPrecioKg();

            if (rbEnvioInternacional.isSelected()) {
                costo = costo + 15.00; // arancel fijo para envío internacional
                txtTiempoEntrega.setText("7 a 10 días hábiles");
            } else if (rbEnvioNacional.isSelected()) {
                txtTiempoEntrega.setText("2 a 3 días hábiles");
            }

            txtCostoTotal.setText(String.valueOf(costo));
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiaEnvioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiaEnvioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiaEnvioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiaEnvioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiaEnvioVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearSolicitud;
    private javax.swing.JButton btnVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<Destinatario> cmbNombresDestinatarios;
    private javax.swing.JComboBox<TarifaPeso> cmbPeso;
    private javax.swing.JLabel lblAlto;
    private javax.swing.JLabel lblAncho;
    private javax.swing.JLabel lblContactoDestinatario;
    private javax.swing.JLabel lblContenidoDeclarado;
    private javax.swing.JLabel lblCostoTotal;
    private javax.swing.JLabel lblDatosDestinatario;
    private javax.swing.JLabel lblDatosRemitente;
    private javax.swing.JLabel lblDestinatario;
    private javax.swing.JLabel lblDetalleEnvio;
    private javax.swing.JLabel lblDetallePaquete;
    private javax.swing.JLabel lblDireccionDestino;
    private javax.swing.JLabel lblDireccionOrigen;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblGuiaEnvio;
    private javax.swing.JLabel lblIdGE;
    private javax.swing.JLabel lblLargo;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblRemitente;
    private javax.swing.JLabel lblTelefonoRemitente;
    private javax.swing.JLabel lblTiempoEntrega;
    private javax.swing.JLabel lblTipoDeEnvio;
    private javax.swing.JLabel lblValorAsegurado;
    private javax.swing.JRadioButton rbEnvioInternacional;
    private javax.swing.JRadioButton rbEnvioNacional;
    private javax.swing.JTextField txtAlto;
    private javax.swing.JTextField txtAncho;
    private javax.swing.JTextField txtContactoDestinatario;
    private javax.swing.JTextField txtContenidoDeclarado;
    private javax.swing.JTextField txtCostoTotal;
    private javax.swing.JTextField txtDireccionDestino;
    private javax.swing.JTextField txtDireccionOrigen;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIdGE;
    private javax.swing.JTextField txtLargo;
    private javax.swing.JTextField txtRemitente;
    private javax.swing.JTextField txtTelefonoRemitente;
    private javax.swing.JTextField txtTiempoEntrega;
    private javax.swing.JTextField txtValorAsegurado;
    // End of variables declaration//GEN-END:variables
}
