/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.GuiaEnvioControlador;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author SUPERTRONICA
 */
public class ReporteVista extends javax.swing.JFrame {

    /**
     * Creates new form ReporteVista
     */
    String[] encabezado = {"Tipo de Envío", "Cantidad"};
    DefaultTableModel modelo = new DefaultTableModel(encabezado, 0);
    ArrayList<Object[]> listaRemitentes = new ArrayList<>();
    ArrayList<Object[]> listaActual = new ArrayList<>();
    JFreeChart graficoActual;

    public ReporteVista() {
        initComponents();
        tblReportes.setModel(modelo);
        tblReportes.setDefaultEditor(Object.class, null);
        cargarCombos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReportes = new javax.swing.JLabel();
        lblFechaInicio = new javax.swing.JLabel();
        lblFechaFin = new javax.swing.JLabel();
        lblRemitente = new javax.swing.JLabel();
        lblTipoEnvio = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        txtFechaFin = new javax.swing.JTextField();
        cmbRemitente = new javax.swing.JComboBox<>();
        cmbTipoEnvio = new javax.swing.JComboBox<>();
        btnPrevisualizar = new javax.swing.JButton();
        btnGenerarPDF = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReportes = new javax.swing.JTable();
        pnlGraficoReporte = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblReportes.setText("REPORTE DE ENVIOS");

        lblFechaInicio.setText("FECHA DE INICIO:");

        lblFechaFin.setText("FECHA DE FIN:");

        lblRemitente.setText("REMITENTE:");

        lblTipoEnvio.setText("TIPO DE ENVIO:");

        btnPrevisualizar.setText("PREVISUALIZAR REPORTE");
        btnPrevisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevisualizarActionPerformed(evt);
            }
        });

        btnGenerarPDF.setText("GENERAR PDF");
        btnGenerarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarPDFActionPerformed(evt);
            }
        });

        tblReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblReportes);

        javax.swing.GroupLayout pnlGraficoReporteLayout = new javax.swing.GroupLayout(pnlGraficoReporte);
        pnlGraficoReporte.setLayout(pnlGraficoReporteLayout);
        pnlGraficoReporteLayout.setHorizontalGroup(
            pnlGraficoReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnlGraficoReporteLayout.setVerticalGroup(
            pnlGraficoReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnPrevisualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenerarPDF)
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFechaInicio)
                    .addComponent(lblFechaFin))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(txtFechaInicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipoEnvio)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblRemitente)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbRemitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblReportes)
                        .addGap(191, 191, 191))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlGraficoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblReportes)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblFechaInicio)
                            .addGap(43, 43, 43))
                        .addComponent(lblFechaFin))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRemitente)
                            .addComponent(cmbRemitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoEnvio)
                            .addComponent(cmbTipoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevisualizar)
                    .addComponent(btnGenerarPDF))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(pnlGraficoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrevisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevisualizarActionPerformed
        // TODO add your handling code here:
        String fechaInicio = txtFechaInicio.getText();
        String fechaFin = txtFechaFin.getText();
        String tipoEnvio = (String) cmbTipoEnvio.getSelectedItem();

        int indiceRemitente = cmbRemitente.getSelectedIndex();
        int idRemitente;
        if (indiceRemitente == 0) {
            idRemitente = 0; // "Todos" está en el índice 0
        } else {
            Object[] fila = listaRemitentes.get(indiceRemitente - 1); // -1 porque "Todos" ocupa el primer lugar
            idRemitente = (int) fila[0];
        }

        GuiaEnvioControlador controlador = new GuiaEnvioControlador();
        System.out.println("DEBUG -> fechaInicio: " + fechaInicio + " | fechaFin: " + fechaFin + " | idRemitente: " + idRemitente + " | tipoEnvio: " + tipoEnvio);
        listaActual = controlador.obtenerDatosReporteSP(fechaInicio, fechaFin, idRemitente, tipoEnvio);

        modelo.setRowCount(0);
        for (Object[] fila : listaActual) {
            modelo.addRow(fila);
        }
        generarGrafico(listaActual);
    }//GEN-LAST:event_btnPrevisualizarActionPerformed

    private void btnGenerarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarPDFActionPerformed
        // TODO add your handling code here:
        if (modelo.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Primero previsualice el reporte");
            return;
        }

        javax.swing.JFileChooser selector = new javax.swing.JFileChooser();
        selector.setSelectedFile(new java.io.File("reporte_envios.pdf"));
        int seleccion = selector.showSaveDialog(this);

        if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION) {
            String ruta = selector.getSelectedFile().getAbsolutePath();

            GuiaEnvioControlador controlador = new GuiaEnvioControlador();
            String nombreRemitente = (String) cmbRemitente.getSelectedItem();
            controlador.generarReportePDF(listaActual, graficoActual, nombreRemitente, ruta);

            JOptionPane.showMessageDialog(null, "Reporte PDF generado correctamente");
        }
    }//GEN-LAST:event_btnGenerarPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    private void cargarCombos() {
        // Combo de tipo de envío
        cmbTipoEnvio.addItem("Todos");
        cmbTipoEnvio.addItem("Nacional");
        cmbTipoEnvio.addItem("Internacional");

        // Combo de remitentes
        cmbRemitente.addItem("Todos");
        GuiaEnvioControlador controlador = new GuiaEnvioControlador();
        listaRemitentes = controlador.listarRemitentes();

        for (Object[] fila : listaRemitentes) {
            cmbRemitente.addItem((String) fila[1]); // fila[1] = nombre
        }
    }

    private void generarGrafico(ArrayList<Object[]> lista) {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (Object[] fila : lista) {
            String tipo = (String) fila[0];
            int cantidad = (int) fila[1];
            dataset.addValue(cantidad, "Cantidad", tipo);
        }

        JFreeChart grafico = ChartFactory.createBarChart(
                "Envíos por Tipo",
                "Tipo de Envío",
                "Cantidad",
                dataset
        );
        graficoActual = grafico;

        ChartPanel panelGrafico = new ChartPanel(grafico);

        pnlGraficoReporte.removeAll();
        pnlGraficoReporte.setLayout(new BorderLayout());
        pnlGraficoReporte.add(panelGrafico, BorderLayout.CENTER);
        pnlGraficoReporte.revalidate();
        pnlGraficoReporte.repaint();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarPDF;
    private javax.swing.JButton btnPrevisualizar;
    private javax.swing.JComboBox<String> cmbRemitente;
    private javax.swing.JComboBox<String> cmbTipoEnvio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblRemitente;
    private javax.swing.JLabel lblReportes;
    private javax.swing.JLabel lblTipoEnvio;
    private javax.swing.JPanel pnlGraficoReporte;
    private javax.swing.JTable tblReportes;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    // End of variables declaration//GEN-END:variables
}
